### ISSUE TITLE
Curse of Vanishing non-armor are unusable

### ISSUE THREAD

**Issue by JustCyra** [kregerl/armorhotswap#11]
Items with the Curse of Vanishing enchantment do not work with this mod on
For example:
Trident with Impaling 5, Riptide 3, Unbreaking 3 and Mending refuses to work if I try to use the riptide part of the trident.

There should be a check for this mod to see if the cursed item being right-clicked is an armor piece if it doesn't do that already

**Comment by kregerl** [comment]
Fixed in forge versions 1.16-1.9, 1.17-1.11, 1.18-1.12
