### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by jpbberry** [kregerl/armorhotswap#3]
Here's a few I encountered;

- Random inability to switch, for no reason at all

- Randomly unable to swap when there's an item in offhand

- Most of the time, it takes two different clicks of the same armor piece to swap it

- Cannot switch with the armor in offhand

**Comment by jpbberry** [comment]
I can reproduce the random inability to switch when there's any item in the off-hand, when I something in my offhand, and if it works, I can equip my elytra, fly around for a few seconds, stop, and am now unable to swap. If I take off my elytra and normal equip my chestplate, it begins working, but I can just fly again and it stops.

**Comment by kregerl** [comment]
Thanks for letting me know about these.
The following have been fixed and released in 1.5:
- Random inability to switch, for no reason at all
- Randomly unable to swap when there's an item in offhand
- Most of the time, it takes two different clicks of the same armor piece to swap it

I am still working on armor swapping in the offhand.

**Comment by jpbberry** [comment]
The issue after flying with an elytra is still not fixed with the newest patch.
Just realized I didn't add it to the buglist. So I'll open up a new issue; #4
