### ISSUE TITLE
After flying with elytra, unable to use armor hotswap

### ISSUE THREAD

**Issue by jpbberry** [kregerl/armorhotswap#4]
I can fix it by taking off the armor piece and right clicking with the new one after, and it begins to work again, but after flying for awhile again it stops working, PFA a video of this happening.
This also extends #3 because when taking the potatos out of my offhand it also begins working again, BUT ONLY when you click on it twice. Which is super weird.
https://www.youtube.com/watch?v=qEVYwMOiChY

**Comment by kregerl** [comment]
Fixed. Thanks
