### ISSUE TITLE
(Fabric Port) Right-click functionalities limited while facing entities

### ISSUE THREAD

**Issue by arf88** [kregerl/armorhotswap#5]
While facing an entity and in interaction range, right-click functions like drawing bows and holding up shields do not activate when clicking.

If the entity has a specific interaction, like name-tagging, riding, flint and steel on a creeper etc, it works normally. Otherwise, it doesn't activate.

Applies to all living entities (likely players too, but untested), doesn't apply to things like dropped items or arrows. It does seem to apply to boats and minecarts, though most of the time the riding function (or furnace menu for furnace minecart, etc.) takes over. Spawner minecarts has this click limitation since it has no innate right-click mechanic, for example.

**Comment by SzczurekYT** [comment]
I also have this issue. And it's pretty big disadventage that I need to aim somewhere else than entity to raise my shield or shoot a crossbow. When we cen expect a fix?

**Comment by SzczurekYT** [comment]
I create a pull request with a fix for this but I'm not sure that this isn't going to break something. When I tested this everything worked fine.

**Comment by kregerl** [comment]
This has been fixed in v1.5, replaced the failing action with a pass.

**Comment by SzczurekYT** [comment]
As I said i'm unfamiliar with modding so it's fine that I failed contributing. For me most important is that the bug is fixed. Thanks

**Comment by kregerl** [comment]
No problem, thanks for contributing in the first place!
